### ISSUE TITLE
Scans `main` as default

### ISSUE THREAD

**Issue by erikkjellgren** [bast/huge#1]
Using this tool in 'older' git-repos where the `main` branch is called `master` gives:

```fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/home/kjellgren/miniconda3/bin/huge", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kjellgren/miniconda3/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kjellgren/miniconda3/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/kjellgren/miniconda3/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kjellgren/miniconda3/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kjellgren/miniconda3/lib/python3.11/site-packages/huge.py", line 48, in main
    commits = get_all_commits_on_branch(branch)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kjellgren/miniconda3/lib/python3.11/site-packages/huge.py", line 15, in get_all_commits_on_branch
    subprocess.check_output(f"git rev-list {branch}", shell=True)
  File "/home/kjellgren/miniconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kjellgren/miniconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git rev-list main' returned non-zero exit status 128.
```

This is when running the tool with no extra options i.e. just:

```huge```

Perhaps, it could be considered to look for both `main` and `master`, or maybe scan the current active branch if possible.

**Comment by bast** [comment]
Thanks! Good idea. Additionally it should give a nicer error message if the branch does not exist instead of such traceback.
